version: "2"

services:
  db:
    image: mysql:5
    container_name: movie_db
    environment:
      MYSQL_DATABASE: movie_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3307:3306"

volumes:
  data:
