version: "2"

services:
  db:
    image: mysql:5
    container_name: movie_db
    environment:
      MYSQL_DATABASE: movie_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3307:3306"

  web:
    build: .
    container_name: movie_web
    command: gunicorn display.wsgi:application --bind 0.0.0.0:8000 -w4
    volumes:
      - .:/usr/src/app/
    env_file: .env
    depends_on:
      - db
    restart: always

  nginx:
    build: ./nginx
    container_name: movie_nginx
    ports:
      - "8001:8000"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    restart: always

volumes:
  data:
